/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_Cqslim */

#ifndef _Included_jni_Cqslim
#define _Included_jni_Cqslim
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_Cqslim
 * Method:    qslimRun
 * Signature: ([F[IF)Ljni/CqsMesh;
 */
JNIEXPORT jobject JNICALL Java_jni_Cqslim_qslimRun___3F_3IF
  (JNIEnv *, jclass, jfloatArray, jintArray, jfloat);

/*
 * Class:     jni_Cqslim
 * Method:    qslimRun
 * Signature: (Ljni/CqsMesh;F)Ljni/CqsMesh;
 */
JNIEXPORT jobject JNICALL Java_jni_Cqslim_qslimRun__Ljni_CqsMesh_2F
  (JNIEnv *, jclass, jobject, jfloat);

#ifdef __cplusplus
}
#endif
#endif
